### ISSUE TITLE
overfeat， Can you help me solve this problem

### ISSUE THREAD

**Issue by HTaCheng** [craymichael/CNN_LCD#10]
![选区_001](https://user-images.githubusercontent.com/47966352/96729494-c8131900-13e7-11eb-965c-7862ae86ebbd.png)

**Comment by craymichael** [comment]
Do you continue to have this problem out of debug mode? There is a strong possibility that this is due to Overfeat giving results that put nans or infs in the similarity matrix. For example, there is issue https://github.com/craymichael/CNN_LCD/issues/1#issuecomment-450522883. It is likely this is on the Overfeat side of things.

**Comment by HTaCheng** [comment]
Thank you very much for your reply. 
Yes, this problem exists whether it is debug mode or not. I have also seen the previous issue, but still can't find a solution.

**Comment by craymichael** [comment]
Hi, I was able to reproduce the issue - I had forgotten what the error messages "looked" like. This is definitely the same issue as I referenced above. Unfortunately, this is an overfeat issue, and it doesn't look like they will fix it, and I am unsure what the problem is as the code used to work fine. See https://github.com/sermanet/OverFeat/issues/39. This is something I will not fix - my recommendation is that you use one of the TensorFlow slim models I describe, or find an implementation of overfeat to replace the sermanet implementation in the code. I apologize that this isn't working, and I will likely archive this project soon as the code is old and isn't planned on being maintained for new versions of libraries.

**Comment by HTaCheng** [comment]
![网络结构014](https://user-images.githubusercontent.com/47966352/99877433-2d516880-2c39-11eb-8e43-4f8c70e8d9fa.png)
How do I get this? If I want to change the network model such as resnet-50, how can I change this?

**Comment by craymichael** [comment]
Hi, only `resnet_v2_152` is available for use. You can specify this on the command-line (run main script with `--help` for all options). If you really want ResNet-50, you will need to modify the code, assuming TF Slim has the model and weights you want. Add the name of the model and its metadata to the `DEFAULT_FEATURE_LAYER`, `MODEL_PARAMS_NAME`, and `MODEL_CKPT_PATHS` dictionaries - follow the other model definitions as guidance.
