### ISSUE TITLE
您好，请问您找到效果不好的原因了吗？

### ISSUE THREAD

**Issue by Geroge-W** [craymichael/CNN_LCD#11]

**Comment by Geroge-W** [comment]
@craymichael

**Comment by craymichael** [comment]
Hi, overfeat is currently broken and I do not intend to fix it. The over models are still supported from TF.slim - try that out. https://github.com/sermanet/OverFeat/issues/39 needs to be resolved in order for overfeat to work, otherwise the implementation needs to be replaced. I will leave that up to someone else.
