### ISSUE TITLE
overfeat failed

### ISSUE THREAD

**Issue by Be997398715** [craymichael/CNN_LCD#13]
I try to use overfeat model by python2 to reconstruct your paper result, however i can't. many problems to deal. could you give the final overfeat pr curve and map as well as other models? thanks for your help.

**Comment by craymichael** [comment]
Hi, as the README states, I am not the author of the paper - I merely implemented the methods as I understood them, so I do not have the exact results from the paper (mine don't fare as well). Furthermore, OverFeat is broken, please see https://github.com/sermanet/OverFeat/issues/39 and my response in another issue https://github.com/craymichael/CNN_LCD/issues/10#issuecomment-718340086.

**Comment by 1274622976** [comment]
If the overfeat model is no longer available, how should this code be modified? Is there any other closed-loop detection code based on deep learning available?Please provide an open source code，thank you!
I'm looking forward to your reply. Thank you for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "craymichael/CNN_LCD"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 下午3:28
收件人:&nbsp;"craymichael/CNN_LCD"<CNN_LCD@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [craymichael/CNN_LCD] overfeat failed (#13)





 
Hi, as the README states, I am not the author of the paper - I merely implemented the methods as I understood them, so I do not have the exact results from the paper (mine don't fare as well). Furthermore, OverFeat is broken, please see sermanet/OverFeat#39 and my response in another issue #10 (comment).

**Comment by craymichael** [comment]
You'd have to modify [cnn_models.py](https://github.com/craymichael/CNN_LCD/blob/master/cnn_models.py) with whatever other implementation that you're able to find. In `get_model_features(...)` you need to override the overfeat model with something that returns feature descriptors for all images (`imgs`). In the smaller version of overfeat, they use the 19th layer, and the 20th layer for the larger model.

I've moved away from SLAM several years ago, so I'm not familiar with what the state-of-the-art looks like. In the past I have used full-blown packages but nothing targetting LCD specifically. I would check out the list of LCD algorithms on PapersWithCode (ranked by GitHub stars): https://paperswithcode.com/task/loop-closure-detection/

**Comment by 1274622976** [comment]
If you use it in Python 2.7, do you need to download the overfeat model? I use tensorflow framework because I just started to learn about closed-loop detection, and I don't know how to change the code. I use Python 3.7, so overfeat display can't be used, but switching to Python 2.7 can't run through the code. In addition, I use GPU, because of the code problem, there is no progress for a long time, hope to get your help, I will be very grateful, looking forward to your reply, thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "craymichael/CNN_LCD"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 下午4:00
收件人:&nbsp;"craymichael/CNN_LCD"<CNN_LCD@noreply.github.com&gt;;
抄送:&nbsp;"浅笑心柔"<1274622976@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [craymichael/CNN_LCD] overfeat failed (#13)





 
You'd have to modify cnn_models.py with whatever other implementation that you're able to find. In get_model_features(...) you need to override the overfeat model with something that returns feature descriptors for all images (imgs). In the smaller version of overfeat, they use the 19th layer, and the 20th layer for the larger model.
 
I've moved away from SLAM several years ago, so I'm not familiar with what the state-of-the-art looks like. In the past I have used full-blown packages but nothing targetting LCD specifically. I would check out the list of LCD algorithms on PapersWithCode (ranked by GitHub stars): https://paperswithcode.com/task/loop-closure-detection/

**Comment by craymichael** [comment]
So, when the implementation did work, it only worked with Python 2.7. Now it doesn't work at all (see the previously linked issues). Unfortunately, unless you are to use the other TF Slim models, overfeat does not work at this time. The TF Slim models should definitely work on GPU
