### ISSUE TITLE
    Sorry,I can not found the models

### ISSUE THREAD

**Issue by yuyuyuyuyu1234** [craymichael/CNN_LCD#4]
hello,my brother :
       I have a issue like that:
       $  python cnn_models.py  -- 
       from models.research.slim.preprocessing.preprocessing_factory import get_preprocessing
       ModuleNotFoundError: No module named 'models'

**Comment by craymichael** [comment]
Please read the README in this repository for how to set up the models properly. https://github.com/craymichael/CNN_LCD/blob/master/README.md

See this:
In order to use the TensorFlow models (everything but OverFeat), you will need to clone the TensorFlow Slim model repository. The easiest way to do so is to clone both this repository and the TensorFlow models repository to the same directory:

git clone https://github.com/tensorflow/models/
git clone <THIS REPO>
Directory structure should look like this:

+ models/
|--- ...
|--- slim
|--- ...
| cnn_lcd.py
| ...
